# Generated by Django 5.2.4 on 2025-08-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('grade', models.CharField(max_length=10)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
